lib/stringify.js, test/stringify.js
The `arrayFormat` option recognizes 3 values: brackets, indices, and
repeat. It defaults to ~~bracket~~ indices.
See the comments in #46
=> Add arrayFormat option

lib/utils.js
I stumbled upon a bug in when using this merge method directly to merge two query param objects with each other containing only string values. 
e.g, target as {userId: "1234"} source as {userId: "64321"}.
This recursively caused the logic for passing strings into objects kick in as follows:
Target = "1234", Source = "64321".
"1234"["64321"] = true;
Hence the modified else clause to be sure that target is an object and not a string.
Regards
Per
=> Fixed issue with recursion and passing strings into objects.

README.md, lib/stringify.js, test/stringify.js
This matches `JSON.stringify()`, which accepts a filter function or property list as its second argument. If a function is specified, it is called to obtain the replacement value. Otherwise, if an array is specified, it is used to select properties and array indices for stringification.
This could be accomplished via a deep copy in user code, but I think it's useful to have—especially since `qs.stringify` traverses the object, anyway.
=> Add a `filter` option

README.md
I did not see the use of `alloDots` option before writing #92 issue.
=> fixes #92 Documenting allowDots option

README.md, dist/qs.js, lib/parse.js, lib/utils.js, test/parse.js, test/stringify.js
this is a short term solution before 5.0.0 which will change everything. Essentially the default behavior will match the 2.x releases, with the difference that you may set the `plainObjects` option to `true` to get the behavior from the 3.x releases.
If you don't want plain objects but also don't want to lose keys that would overwrite prototype properties, you can set the `prefixPrototypes` option to `true` and those keys will be prefixed with an underscore `'_'` and passed along. It's not perfect, but at least the keys aren't silently ignored.
Would appreciate your feedback on this one @hueniverse @dougwilson
=> make returning plain objects and allowing prototype overwriting properties optional

.npmignore
I use npm for AMD. qs is only library from my front-end deps which doesn't include dist in npm package.
=> include dist to npm

README.md, lib/stringify.js, test/stringify.js
I was getting frustrated having `null` values in a query object and having to replace them all with `undefined` to get the query string to render the way I wanted. This should fix that problem, by adding a `skipNull` flag to `stringify`, which essentially makes null values act as if they were `undefined` for the purposes of stringifying.
=> Add flag `skipNulls` to optionally skip null values in stringify

lib/stringify.js, test/stringify.js
This option is needed when we want to create predictable query strings.
=> Add an option to sort the keys in the query string FIX #64

package.json
npm doesn't seem to understand it (no warning).
=> Fix engines definition

.eslintrc, dist/qs.js, lib/stringify.js, test/stringify.js
Added allowDots option for stringify. I have added a new test case for the same.
=> allowDots option for stringify. Tests also updated.

README.md, package.json
I recently publish [qs-iconv](https://github.com/martinheidegger/qs-iconv) that should make it very easy to transform querystrings to a different character encoding. This PR adds the documentation on how to use it to `qs` as well since this is likely a reoccurring issue.
=> Added documentation on how to use qs-iconv with qs

CONTRIBUTING.md
The referenced document was moved into `.github` directory. This changes the link to point to its new location.
=> fix link to contributing document

README.md
#164 has non-issue tag.
As my original expectation is `assert.equal(qs.stringify({ a: {} }), 'a');`
but actually is  `assert.equal(qs.stringify({ a: {} }), '');`
so I think it should be documented.
=> add empty object and array values example.

.eslintrc, README.md, lib/stringify.js, test/stringify.js
linked to #198 and #171 
stringify option for doNotEncodeKeys that defaults to false, and when it is true, it skips the encoder call entirely for anything that's a key.
=> encodeValuesOnly option

lib/utils.js, test/parse.js
=> fix: follow allowPrototypes during merge

.eslintrc, README.md, lib/parse.js, lib/stringify.js, test/parse.js, test/stringify.js
The primary motivation for this change is that react-router v4 returns the `location.search` property with a leading question mark. Whilst it's trivial to remove this, it's nicer still to have the library handle it.
=> [New] Prefix option for parse function

lib/parse.js
Avoid running the same `indexOf(']=')` operation twice by storing the result and reusing in the else statement.
=> remember index to reuse in else statement; avoid recalling indexOf

.eslintrc, lib/stringify.js, test/stringify.js
Submitting PR as agreed, this should fix the issue described in #213:
Stringifying an empty object would produce a string such as '?'. With
this fix, we output an empty string instead.
Sorry about increasing complexity and max-statements in `.eslintrc`,
I didn't see a quick way to reduce complexity.
Thanks for this great library 👍
=> Handle stringifying empty objects with addQueryPrefix

.travis.yml
My PR #224 is failing on Node.js 0.6 because Travis CI recently swapped out the distro from Precise to Trusty, and the Node.js 0.6 source is failing to compile. There may be another choice, but this is what I've been doing for my modules, at least.
=> Use precise dist for Node.js 0.6 runtime

lib/parse.js, lib/utils.js, test/parse.js
This is a change of the internal `compact` utility to use an iterative approach instead of recursion in order to better handle very, very deep objects without a stack overflow. It was noticed on CharkaCore because it has a much smaller maximum stack than v8 does, though it can still happen on v8 (which the test does).
/cc @kunalspathak
=> Fix parsing & compacting very deep objects

lib/utils.js
Hello.
free `exports` usage (when it is not assignmnet for really exporting something) confusing rollup to wrap such modules in additional wrappers.
This PR remove `exports` for self referencing exporting symbols.
Thanks.
What do you think about replacing build with rollup (i mean dist/qs.js) - it will produce smaller file, and much readable/debuggable? (i can prepare PR)
=> Change exports usage

lib/stringify.js, test/stringify.js
Fixes https://github.com/ljharb/qs/issues/278
=> Allow `strictNullHandling` to work when using a custom filter

lib/stringify.js
Currently `qs.stringify` will create a new array whenever a new parameter is added. This fixes it by pushing to the existing one instead.
Very unscientific benchmark:
```
time node -e "const qs = require('./');for (let i = 0 ; i < 1000000 ; i += 1)qs.stringify({a: 1, b: 2, c: 3, d: 4, e: 5, f: 6, g: 7, h: 8, i: 9, j: 10, k: 11, l: 12, m: 13, n: 14, o: 15, p: 16, q: 17, r: 18, s: 19, t: 20, u: 21, v: 22, x: 23, y: 24, z: 25});"
```
Before:
```
real	0m11.247s
user	0m11.260s
sys	0m0.093s
```
After:
```
real	0m6.291s
user	0m6.305s
sys	0m0.052s
```
=> stringify: Avoid arr = arr.concat(...), push to the existing instance

README.md, lib/parse.js, lib/stringify.js, test/parse.js, test/stringify.js
It is a common feature request to parse array in 'comma' format, like #219 .
Simple allow we passed a function to arrayFormat, as #275 described, could not work, as 'comma' actually alter the left-side of equation, in a way that join the values of array rather than list them with well-structured key.  
In turn I create this new PR as an alternative way to solve it. However, it is still suffered some designed issue.
It would be hard to determine that how we represent complex array, such as `a=[{b: 'c'}]` in comma format. I simply use `JSON.stringify` to deal with inner objects, but I believe that there should be more common acknowledge to discuss about it.
Fortunately, most use-case of comma format would treat the values of array as a plain string, in turn there would be no problem with my …
=> add comma as an arrayFormat option

lib/parse.js, test/parse.js
@ljharb Edit: this PR now adds tests for the current useless behavior of depth 0, and then fixes it. Fixes #261.
```
//当options.depth为空时,按&符进行分割
assert.deepEqual(qs.parse('ids[0]=1&ids[1]=2&ids[2]=3', { depth: 0 }), { 'ids[0]': 1, 'ids[1]': 2, 'ids[2]': 3 })
```
测试已经通过
我觉得这可以作为一个补充规则
=> Fix `depth: 0`, add `depth: false`

lib/parse.js, test/parse.js
in case of comma enabled .. parsing should check for strings only when using indexOf(',')
fixes: #328
=> [fix] comma option enabled value parsing to use strings only

lib/parse.js, test/parse.js
=> [fix] parsing a field that holds array of arrays

lib/parse.js, test/parse.js
Fixes issue with parsing array with `{comma: true}` option when query string is passed as an object.
Discussed in https://github.com/ljharb/qs/issues/357
=> Fix issue with parsing array from object

lib/parse.js, test/parse.js
changes on the default decoder to correctly parse comma delimited strings while having percent encoded comma
Fixes #311.
=> [fix] parsing comma delimited str with percent encoded comma

lib/parse.js, test/parse.js
Followup PR to #336. Fixes #311.
=> [Fix] proper comma parsing of URL-encoded comma

lib/stringify.js, test/stringify.js
Fixed #310 
continued from PR #317
=> `stringify`: fix arrayFormat comma with empty array/objects

README.md, lib/parse.js, test/parse.js, test/stringify.js
=> [New] `parse`: add `allowSparse` option for collapsing arrays with missing indices

.github/workflows/node-4+.yml, .github/workflows/node-iojs.yml, .github/workflows/node-pretest.yml, .github/workflows/node-zero.yml, README.md
This part was a little confusing when I was reading through the doc.
=> [meta] fix README.md

.editorconfig, README.md
This should hopefully lay to rest #91
=> [Docs] add note and links for coercing primitive values

lib/stringify.js, test/stringify.js
Following changes were made:
* According to the documentation when `encodeValuesOnly = true`, then all characters except the values must not be encoded. This includes brackets and joining characters such as comma. It works perfectly for all other characters except when comma is used to join elements of an array. Then even the comma is encoded. 
* One of the tests had a bug where we assumed the result of `qs.stringify({ a: ['b', 'c', 'd'] }, { arrayFormat: 'comma' })` to be equal to `'a=b,c,d'`. Which is not the expected behavior as for the comma to not be encoded we must either set `encode: false` or `encodeValuesOnly: true`. So the right result would be `'a=b%2Cc%2Cd'` as the default functionality of the function is to encode the complete string.
=> Fixes the issue of stringify encoding comma(used to join array) even when `encodeValuesOnly = true`

lib/stringify.js, test/stringify.js
With all the testing, I think this is the ultimate solution for circular references.
Fixes #403.
=> [Fix] `stringify`: actually fix cyclic references

lib/stringify.js
_I just removed needless(for these cases) `typeof` for checking for undefined_
update: Added checking for typeof in parser.
=> [Robustness] `stringify`: avoid relying on a global `undefined`

lib/stringify.js, test/parse.js, test/stringify.js
=> [Fix] `stringify`: with `arrayFormat: comma`, include an explicit `[]` on a single-item array

README.md
Add to README.md the usage of option `filter` for injecting custom serialization, i.e. of custom types.
=> [readme] add usage of `filter` option for injecting custom serialization, i.e. of custom types

.eslintrc, README.md, lib/parse.js, lib/stringify.js, test/parse.js, test/stringify.js
This PR adds `allowEmptyArrays` option which let's you keep empty arrays in the object values and address [this issue](https://github.com/ljharb/qs/issues/362)
Without `allowEmptyArrays` option
```
qs.stringify({ foo: [], bar: baz }) // 'bar=baz'
qs.parse(qs.stringify({ foo: [], bar: baz })) // { bar: baz }
```
With `allowEmptyArrays` options set to true
```
qs.stringify({ foo: [], bar: baz }, { allowEmptyArrays: true }) // 'foo[]&bar=baz'
qs.parse(qs.stringify({ foo: [], bar: baz })) // { foo: [], bar: baz }
```
=> [New] `parse`/`stringify`: add `allowEmptyArrays` option to allow [] in object values

.eslintrc, README.md, lib/parse.js, lib/stringify.js, test/parse.js, test/stringify.js
Previously the dot in the keys would be encoded but the round-tripping was broken. Here is the previous behavior
```javascript
const opts = { allowDots: true };
qs.parse(qs.stringify({ "name.obj": { "first": "John", "last": "Doe" } }, opts), opts)
// => { name: { obj: { first: 'John', last: 'Doe' } } }
```
This PR fixes the above behavior and fixes #249:
```javascript
qs.parse(qs.stringify({ "name.obj": { "first": "John", "last": "Doe" } }, { allowDots: true, encodeDotKeys: true }), { allowDots: true, decodeDotKeys: true })
{ 'name.obj': { first: 'John', last: 'Doe' } }
```
=> [New] `stringify`/`parse`: add `encodeDotKeys`/`decodeDotKeys` respectively to allow . in object keys

lib/parse.js, test/parse.js
I noticed that url-encoded square brackets, i.e. `%5B` and `%5D`, do not get correctly parsed in this case
```javascript
t.test(
'parses encoded brackets holds array of arrays when having two parts of strings with comma as array divider',
function (st) {
st.deepEqual(
// foo[]=1,2,3&foo[]=4,5,6
qs.parse('foo%5B%5D=1,2,3&foo%5B%5D=4,5,6', { comma: true }), 
{ foo: [['1', '2', '3'], ['4', '5', '6']] }
);
st.deepEqual(
// foo[]=1,2,3&foo[]=
qs.parse('foo%5B%5D=1,2,3&foo%5B%5D=', { comma: true }), 
{ foo: [['1', '2', '3'], ''] }
);
st.deepEqual(
// foo[]=1,2,3&foo[]=
qs.parse('foo%5B%5D=1,2,3&foo%5B%5D=,', { comma: true }), 
{ foo: [['1', '2', '3'], ['', '']] }
);
st.deepEqual(
// foo[]=1,2,3&foo[]=a
qs.parse('foo%5B%5D=1,2,3&foo%5B%5D=a', { comma: true }),
{ foo: [['1', '2', '3'], 'a'] }
); …
```
=> fix: parse url-encoded square brackets

README.md, lib/parse.js, test/parse.js
This PR proposes an option (`strictDepth`) to enforce throwing when input depth is beyond the `depth` option.
Defaults to `false`
Throws RangeError.
if `depth` has been set by the user to 0, we do not throw, but fallback to the previous behavior.
=> [New] add strictDepth option to throw when input is beyond depth

README.md, lib/parse.js, test/parse.js
As discussed in https://github.com/expressjs/express/issues/5878 about adding an option to enable throwing error when parameter limit exceeded, I have, 
Additionally, as https://github.com/ljharb/qs/issues/515 suggests about throwing an error in case of any limit is exceeded, it has been implemented as well.
1. Fixes https://github.com/ljharb/qs/issues/515
=> [New]: `parse`: add `throwOnLimitExceeded` option
